import { useState } from 'react';
import type { FlashcardProps } from '../types';

export const Flashcard = ({ flashcard }: FlashcardProps) => {
  const [isFlipped, setIsFlipped] = useState(false);

  return (
    <div 
      className="bg-white rounded-xl shadow-lg p-6 cursor-pointer transition-all duration-300 hover:shadow-xl border-2 border-gray-200 min-h-[200px] flex items-center justify-center"
      onClick={() => setIsFlipped(!isFlipped)}
    >
      <div className="text-center">
        {!isFlipped ? (
          <div>
            <h3 className="text-2xl font-bold text-gray-800 mb-2">
              {flashcard.topic}
            </h3>
            <p className="text-sm text-gray-500 mt-4">
              Click to see explanation
            </p>
          </div>
        ) : (
          <div>
            <h4 className="text-lg font-semibold text-blue-600 mb-3">
              {flashcard.topic}
            </h4>
            <p className="text-gray-700 leading-relaxed">
              {flashcard.explanation || 'Explanation will be generated by LLM...'}
            </p>
            <p className="text-sm text-gray-500 mt-4">
              Click to flip back
            </p>
          </div>
        )}
      </div>
    </div>
  );
};

